import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#44474d",
        primary: "#000000",
        "outline-variant": "#c5c6cd",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeeef",
        "surface-dim": "#d9dadb",
        "secondary-fixed": "#cde5ff",
        "surface-tint": "#515f78",
        surface: "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "tertiary-container": "#3b0900",
        "on-secondary-fixed": "#001d32",
        "secondary-container": "#67bafd",
        "primary-fixed": "#d6e3ff",
        "on-secondary-fixed-variant": "#004b74",
        "on-surface": "#191c1d",
        "tertiary-fixed-dim": "#ffb5a0",
        "secondary-fixed-dim": "#94ccff",
        tertiary: "#000000",
        "primary-container": "#0d1c32",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b9c7e4",
        "on-tertiary-fixed-variant": "#862200",
        "on-primary-fixed": "#0d1c32",
        outline: "#75777e",
        "surface-container-high": "#e7e8e9",
        secondary: "#006399",
        "tertiary-fixed": "#ffdbd1",
        background: "#f8f9fa",
        "on-tertiary-container": "#ed4a14",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#39475f",
        "error-container": "#ffdad6",
        "on-secondary-container": "#004972",
        "on-error-container": "#93000a",
        "on-primary-container": "#76849f",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#b9c7e4",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        // These allow font-display-lg etc. as font-family classes
        "display-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        base: "8px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
