/**
 * Burnaby Palace Restaurant — Complete Menu Seed with Images
 * Run: node_modules\.bin\tsx.cmd seed/seed-menu.ts
 */
import mongoose from 'mongoose';
import { readFileSync } from 'fs';
import { resolve } from 'path';

try {
  const env = readFileSync(resolve(process.cwd(), '.env.local'), 'utf-8');
  for (const line of env.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const idx = t.indexOf('=');
    if (idx === -1) continue;
    const k = t.slice(0, idx).trim();
    const v = t.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[k]) process.env[k] = v;
  }
} catch { /* ignore */ }

const URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/burnaby-palace';

const CatSchema = new mongoose.Schema({ name: String, slug: { type: String, unique: true }, description: String, sortOrder: { type: Number, default: 0 }, isActive: { type: Boolean, default: true } }, { timestamps: true });
const ItemSchema = new mongoose.Schema({ name: String, slug: { type: String, unique: true }, description: String, price: Number, category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' }, image: String, isAvailable: { type: Boolean, default: true }, isFeatured: { type: Boolean, default: false }, sortOrder: { type: Number, default: 0 } }, { timestamps: true });

const Cat  = mongoose.models.Category || mongoose.model('Category', CatSchema);
const Item = mongoose.models.MenuItem  || mongoose.model('MenuItem',  ItemSchema);

const I = '/images/menu/'; // base path

// ─── CATEGORIES ───────────────────────────────────────────────────────────────
const CATS = [
  { name: 'Fried Rice 炒饭',              slug: 'fried-rice',       description: 'Wok-fried rice dishes',              sortOrder: 1  },
  { name: 'Soft Chow Mein 炒面',          slug: 'soft-chow-mein',   description: 'Soft stir-fried noodle dishes',      sortOrder: 2  },
  { name: 'Group Dinners 套餐',           slug: 'group-dinners',    description: 'Set meals for groups',               sortOrder: 3  },
  { name: 'Crispy Chow Mein 脆炒面',      slug: 'crispy-chow-mein', description: 'Crispy fried noodle dishes',         sortOrder: 4  },
  { name: 'Pork or Spareribs 猪肉排骨',   slug: 'pork',             description: 'Pork and spareribs dishes',          sortOrder: 5  },
  { name: 'Soups 汤',                     slug: 'soups',            description: 'Classic Chinese soups',              sortOrder: 6  },
  { name: 'Beef 牛肉',                    slug: 'beef',             description: 'Beef entrées',                       sortOrder: 7  },
  { name: 'Chicken 鸡肉',                 slug: 'chicken',          description: 'Chicken entrées',                    sortOrder: 8  },
  { name: 'Appetizers 头盘',              slug: 'appetizers',       description: 'Starters and snacks',                sortOrder: 9  },
  { name: 'Over Steamed Rice 烩饭',       slug: 'over-steamed-rice',description: 'Entrées over steamed rice',          sortOrder: 10 },
  { name: 'Dim Sum 点心',                 slug: 'dim-sum',          description: 'Traditional dim sum',                sortOrder: 11 },
  { name: 'Vegetables 蔬菜',              slug: 'vegetables',       description: 'Vegetarian dishes',                  sortOrder: 12 },
  { name: 'Seafood 海鲜',                 slug: 'seafood',          description: 'Fresh seafood dishes',               sortOrder: 13 },
  { name: 'Noodle Soup 汤面',             slug: 'noodle-soup',      description: 'Hot noodle soups',                   sortOrder: 14 },
  { name: 'Side Orders / Misc. 配菜',     slug: 'sides',            description: 'Sides and sauces',                   sortOrder: 15 },
  { name: 'Soft Drinks 饮料',             slug: 'drinks',           description: 'Canned pops and bottled water',      sortOrder: 16 },
  { name: 'Hot Pot 煲仔',                 slug: 'hot-pot',          description: 'Clay pot dishes',                    sortOrder: 17 },
  { name: 'Duck 鸭肉',                    slug: 'duck',             description: 'BBQ duck',                           sortOrder: 18 },
  { name: 'Bean Curd / Tofu 豆腐',        slug: 'tofu',             description: 'Tofu and bean curd dishes',          sortOrder: 19 },
  { name: 'Egg 蛋类',                     slug: 'egg',              description: 'Egg dishes',                         sortOrder: 20 },
];

// ─── ITEMS ─────────────────────────────────────────────────────────────────────
// { name, slug, description, price, cat, img, featured, sort }
type Row = { name:string; slug:string; description:string; price:number; cat:string; img:string; featured:boolean; sort:number };

const ITEMS: Row[] = [
  // ── FRIED RICE ──
  { name:'R6. House Fried Rice 扬州炒饭',                      slug:'house-fried-rice',                    description:'Our most popular fried rice with egg, shrimps, and BBQ pork.',                                           price:16.25, cat:'fried-rice',        img:I+'house-fried-rice.jpg',                                 featured:true,  sort:1  },
  { name:'R12. Seafood Fried Rice 海鲜炒饭',                   slug:'seafood-fried-rice',                  description:'Chopped scallop, fish, shrimp, green onion, head lettuce, carrot, and egg.',                             price:19.25, cat:'fried-rice',        img:I+'seafood-fried-rice.jpg.png',                           featured:false, sort:2  },
  { name:'R4. BBQ Pork Fried Rice 叉烧炒饭',                   slug:'bbq-pork-fried-rice',                 description:'BBQ pork, green onion, head lettuce, carrot, and egg.',                                                  price:15.50, cat:'fried-rice',        img:I+'bbq-pork-fried-rice.jpg',                              featured:false, sort:3  },
  { name:'R8. Curried Chicken Fried Rice 咖喱鸡炒饭',          slug:'curried-chicken-fried-rice',          description:'Shredded chicken, green onion, head lettuce, carrot, and egg. Curried flavour. Spicy.',                   price:16.00, cat:'fried-rice',        img:I+'curried-chicken-fried-rice.jpg',                       featured:false, sort:4  },
  { name:'R1. Plain Egg Fried Rice 鲜蛋炒饭',                  slug:'plain-egg-fried-rice',                description:'Green onion, head lettuce, carrot, and egg. No meat.',                                                   price:15.50, cat:'fried-rice',        img:I+'plain-egg-fried-rice.jpg.png',                         featured:false, sort:5  },
  { name:'R3. Beef Fried Rice 牛肉炒饭',                       slug:'beef-fried-rice',                     description:'Minced beef, green onion, head lettuce, carrot, and egg.',                                               price:15.50, cat:'fried-rice',        img:I+'beef-fried-rice.jpg.png',                              featured:false, sort:6  },
  { name:'R10. Beef & Tomato Fried Rice 番茄牛炒饭',           slug:'beef-tomato-fried-rice',              description:'Sliced beef and tomato on a bedding of egg fried rice.',                                                 price:16.25, cat:'fried-rice',        img:I+'beef-tomato-fried-rice.jpg.png',                       featured:false, sort:7  },
  { name:'R14. Dried Scallop & Egg White Fried Rice 瑶柱蛋白炒饭',slug:'dried-scallop-egg-white-fried-rice',description:'Dried scallop, green onion, head lettuce, carrot, and egg white.',                                    price:21.25, cat:'fried-rice',        img:'',                                                       featured:false, sort:8  },
  { name:'R13. Chicken & Salty Fish Fried Rice 咸鱼鸡粒炒饭',  slug:'chicken-salty-fish-fried-rice',       description:'Shredded chicken, salted fish, green onion, head lettuce, carrot, and egg.',                              price:17.75, cat:'fried-rice',        img:'',                                                       featured:false, sort:9  },
  { name:'R2. Chicken Fried Rice 鸡丝炒饭',                    slug:'chicken-fried-rice',                  description:'Shredded chicken, green onion, head lettuce, carrot, and egg.',                                          price:15.50, cat:'fried-rice',        img:I+'chicken-fried-rice.jpg.png',                           featured:false, sort:10 },
  { name:'R9. Szechuan Spicy Fried Rice 四川炒饭',             slug:'szechuan-spicy-fried-rice',           description:'Shredded chicken and shrimp with ketchup and Sriracha. Spicy.',                                         price:16.25, cat:'fried-rice',        img:I+'szechuan-spicy-fried-rice.jpg.png',                    featured:false, sort:11 },
  { name:'R7. Vegetarian Fried Rice 杂菜炒饭',                 slug:'vegetarian-fried-rice',               description:'Chopped vegetables and egg.',                                                                            price:15.50, cat:'fried-rice',        img:I+'vegetarian-fried-rice.jpg.png',                        featured:false, sort:12 },
  { name:'R11. Chicken & Pineapple Fried Rice 菠萝鸡炒饭',     slug:'chicken-pineapple-fried-rice',        description:'Shredded chicken, pineapple chunks, green onion, head lettuce, carrot, and egg.',                        price:16.25, cat:'fried-rice',        img:I+'chicken-pineapple-fried-rice.jpg.png',                 featured:false, sort:13 },
  { name:'R5. Shrimp Fried Rice 虾仁炒饭',                     slug:'shrimp-fried-rice',                   description:'Shrimp, green onion, head lettuce, carrot, and egg.',                                                   price:16.25, cat:'fried-rice',        img:I+'shrimp-fried-rice.jpg.png',                            featured:false, sort:14 },

  // ── SOFT CHOW MEIN ──
  { name:'M16. Stir Fried Chow Mein with Chicken 豉油皇炒面',   slug:'stir-fried-chow-mein-chicken',        description:'Shredded chicken, bean sprouts, onion, and green onion stir fried with noodles.',                           price:16.75, cat:'soft-chow-mein',    img:I+'stir-fried-chow-mein-chicken.jpg',                     featured:false, sort:1  },
  { name:'M30. Fried Rice Noodle with Mixed Seafood 海鲜烩河',  slug:'rice-noodle-mixed-seafood',           description:'Scallops, prawns, fish fillets, squid, and mixed vegetables on rice noodles.',                            price:21.50, cat:'soft-chow-mein',    img:I+'rice-noodle-mixed-seafood.jpg.png',                    featured:false, sort:2  },
  { name:'M18. Shanghai Noodle Chow Mein with Pork 上海粗炒面', slug:'shanghai-noodle-pork',                description:'Thick noodles with cabbage and pork.',                                                                    price:16.75, cat:'soft-chow-mein',    img:I+'shanghai-noodle-pork.jpg.png',                         featured:false, sort:3  },
  { name:'M23. Fried Rice Noodle with Bok Choy & Chicken 菜远鸡河',slug:'rice-noodle-bok-choy-chicken',    description:'Sliced chicken and baby bok choy with gravy on rice noodles.',                                            price:17.75, cat:'soft-chow-mein',    img:I+'rice-noodle-bok-choy-chicken.jpg.png',                 featured:false, sort:4  },
  { name:'M19. Singapore Curried Rice Noodle 星洲炒米',         slug:'singapore-curried-rice-noodle',       description:'Vermicelli rice noodles with BBQ pork, shrimp, eggs, bell pepper, and bean sprouts.',                     price:17.25, cat:'soft-chow-mein',    img:I+'singapore-curried-rice-noodle.jpg.png',                featured:true,  sort:5  },
  { name:'M31. Fried Yee Mein with Chicken 鸡丝伊面',           slug:'fried-yee-mein-chicken',              description:'Shredded chicken, black mushroom, snow pea, and yee mein.',                                              price:18.25, cat:'soft-chow-mein',    img:I+'fried-yee-mein-chicken.jpg.png',                       featured:false, sort:6  },
  { name:'M32. Fried Homestyle Rice Cake with Pork 家乡炒年糕', slug:'homestyle-rice-cake-pork',            description:'Shredded pork, snow pea, carrot, and rice cake.',                                                        price:17.75, cat:'soft-chow-mein',    img:I+'homestyle-rice-cake-pork.jpg.png',                     featured:false, sort:7  },
  { name:'M21. Fried Rice Noodle with Chicken 干炒鸡河',        slug:'rice-noodle-chicken',                 description:'Flat rice noodles with chicken, bean sprouts, onion, and green onion.',                                   price:17.25, cat:'soft-chow-mein',    img:I+'rice-noodle-chicken.jpg.png',                          featured:false, sort:8  },
  { name:'M25. Fried Rice Noodle Chicken in Black Bean 豉汁鸡河',slug:'rice-noodle-chicken-black-bean',     description:'Sliced chicken with mushroom, bell pepper, and onion in garlic black bean sauce on rice noodles.',         price:17.75, cat:'soft-chow-mein',    img:I+'rice-noodle-chicken-black-bean.jpg.png',               featured:false, sort:9  },
  { name:'M20. Fried Rice Noodle with Beef 干炒牛河',           slug:'rice-noodle-beef',                    description:'Flat rice noodles with beef, bean sprouts, onion, and green onion.',                                      price:17.25, cat:'soft-chow-mein',    img:I+'rice-noodle-beef.jpg.png',                             featured:true,  sort:10 },
  { name:'M17. Stir Fried Chow Mein with Vegetables 杂菜捞面',  slug:'stir-fried-chow-mein-veg',            description:'Vegetarian. Mixed vegetables, bean sprouts, and noodles.',                                               price:16.75, cat:'soft-chow-mein',    img:I+'stir-fried-chow-mein-veg.jpg.png',                     featured:false, sort:11 },
  { name:'M28. Fried Rice Noodle Chicken & Vegetables 鸡杂菜炒河',slug:'rice-noodle-chicken-veg',           description:'Sliced chicken with mixed vegetables on rice noodles.',                                                  price:17.75, cat:'soft-chow-mein',    img:I+'rice-noodle-chicken-veg.jpg.png',                      featured:false, sort:12 },
  { name:'M27. Fried Rice Noodle Beef & Mixed Vegetables 牛杂菜炒河',slug:'rice-noodle-beef-veg',           description:'Sliced beef with mixed vegetables on rice noodles.',                                                     price:17.75, cat:'soft-chow-mein',    img:I+'rice-noodle-beef-veg.jpg.png',                         featured:false, sort:13 },
  { name:'M29. Fried Rice Noodle with Egg & Shrimps 虾仁烩河',  slug:'rice-noodle-egg-shrimp',              description:'Prawns and egg on rice noodles.',                                                                        price:19.75, cat:'soft-chow-mein',    img:I+'rice-noodle-egg-shrimp.jpg.png',                       featured:false, sort:14 },
  { name:'M24. Fried Rice Noodle Beef in Black Bean 豉汁牛河',   slug:'rice-noodle-beef-black-bean',         description:'Sliced beef with mushroom, bell pepper, and onion in garlic black bean sauce on rice noodles.',           price:17.75, cat:'soft-chow-mein',    img:I+'rice-noodle-beef-black-bean.jpg.png',                  featured:false, sort:15 },
  { name:'M22. Fried Rice Noodle Bok Choy & Beef 菜远牛河',     slug:'rice-noodle-bok-choy-beef',           description:'Sliced beef and baby bok choy with gravy on rice noodles.',                                              price:17.75, cat:'soft-chow-mein',    img:I+'rice-noodle-bok-choy-beef.jpg.png',                    featured:false, sort:16 },

  // ── GROUP DINNERS ──
  { name:'Dinner for 2A',  slug:'dinner-for-2a',  description:'2 Vegetarian Egg Rolls, Chicken Fried Rice, Buddha\'s Feast, Sweet and Sour Boneless Pork.',                                                                                                        price:40.50,  cat:'group-dinners', img:I+'Dinner-for-2A.png',     featured:false, sort:1 },
  { name:'Dinner for 2B',  slug:'dinner-for-2b',  description:'2 Vegetarian Egg Rolls, Stir-Fried Chow Mein with Chicken, Buddha\'s Feast, Sweet and Sour Boneless Pork.',                                                                                         price:40.50,  cat:'group-dinners', img:I+'dinner-for-2b.png',     featured:false, sort:2 },
  { name:'Dinner for 3A',  slug:'dinner-for-3a',  description:'3 Vegetarian Egg Rolls, Chicken Fried Rice, Buddha\'s Feast, Breaded Lemon Chicken, Ginger Fried Beef.',                                                                                             price:57.50,  cat:'group-dinners', img:I+'Dinner-for-3A.png',     featured:false, sort:3 },
  { name:'Dinner for 3B',  slug:'dinner-for-3b',  description:'3 Vegetarian Egg Rolls, Stir-Fried Chow Mein with Chicken, Buddha\'s Feast, Breaded Lemon Chicken, Ginger Fried Beef.',                                                                             price:57.50,  cat:'group-dinners', img:I+'dinner-for-3b.png',     featured:false, sort:4 },
  { name:'Group Dinners 4',slug:'dinner-for-4',   description:'4 Vegetarian Egg Rolls, Beef and Broccoli Chow Mein, Chicken Fried Rice, Prawns with Mixed Veggies, House Special Chicken.',                                                                         price:84.00,  cat:'group-dinners', img:I+'Group-Dinners-4.png',   featured:false, sort:5 },
  { name:'Group Dinners 6',slug:'dinner-for-6',   description:'6 Vegetarian Egg Rolls, Beef Lettuce Wraps, House Fried Rice, Seafood Chow Mein, Buddha\'s Feast, Deep Fried Prawns with Sweet and Sour Sauce, Ginger Fried Beef.',                                 price:134.00, cat:'group-dinners', img:I+'group-dinners-6.png',   featured:true,  sort:6 },
  { name:'Group Dinners 8',slug:'dinner-for-8',   description:'8 Vegetarian Egg Rolls, Beef Lettuce Wraps, House Fried Rice, House Special Chow Mein, Honey Garlic Boneless Pork, Buddha\'s Feast, Sliced Beef and Broccoli, Prawns in Black Bean Sauce, House Special Chicken.', price:188.00, cat:'group-dinners', img:I+'group-dinners-8.png',   featured:false, sort:7 },
  { name:'Group Dinners 10',slug:'dinner-for-10', description:'10 Vegetarian Egg Rolls, Beef Lettuce Wraps, House Fried Rice, House Special Chow Mein, Honey Garlic Boneless Pork, Buddha\'s Feast, Sliced Beef and Broccoli, Pineapple Sweet and Sour Chicken Balls, Chef\'s Special Mixed Seafood, House Special Chicken.', price:215.00, cat:'group-dinners', img:I+'group-dinners-10.png', featured:false, sort:8 },

  // ── CRISPY CHOW MEIN ──
  { name:'M4. Vegetarian Chow Mein 杂菜炒面',                  slug:'veg-chow-mein',                       description:'Mixed vegetables on crispy noodles.',                                                                    price:16.75, cat:'crispy-chow-mein',  img:I+'vegetarian-chow-mein.png',                             featured:false, sort:1  },
  { name:'M8. Chicken & Veggies Chow Mein 鸡杂菜炒面',         slug:'chicken-veg-chow-mein',               description:'Sliced chicken and mixed vegetables on crispy noodles.',                                                 price:17.25, cat:'crispy-chow-mein',  img:I+'chicken-and-veggies-chow-mein.png',                    featured:false, sort:2  },
  { name:'M11. Chicken in Black Bean Sauce Chow Mein 豉汁鸡炒面',slug:'chicken-black-bean-chow-mein',      description:'Sliced chicken with mushroom, bell pepper, and onion in black bean sauce on crispy noodles.',              price:17.25, cat:'crispy-chow-mein',  img:I+'chicken-in-black-bean-sauce-chow-mein.png',            featured:false, sort:3  },
  { name:'M7. BBQ Pork & Veggies Chow Mein 叉烧杂菜炒面',      slug:'bbq-pork-veg-chow-mein',              description:'BBQ pork and mixed vegetables on crispy noodles.',                                                       price:17.25, cat:'crispy-chow-mein',  img:I+'bbq-pork-and-veggies-chow-mein.png',                   featured:false, sort:4  },
  { name:'M33. Beef & Tomato Chow Mein 番茄牛炒面',             slug:'beef-tomato-chow-mein',               description:'Sliced beef and tomato on crispy noodles.',                                                              price:17.25, cat:'crispy-chow-mein',  img:I+'beef-and-tomato-chow-mein.png',                        featured:false, sort:5  },
  { name:'M3. Sliced Beef Chow Mein 牛肉炒面',                  slug:'sliced-beef-chow-mein',               description:'With napa cabbage, bamboo shoot, and bean sprouts on crispy noodles.',                                   price:16.75, cat:'crispy-chow-mein',  img:I+'sliced-beef-chow-mein.png',                            featured:false, sort:6  },
  { name:'M5. Beef & Broccoli Chow Mein 牛百加利炒面',          slug:'beef-broccoli-chow-mein',             description:'Sliced beef and broccoli on crispy noodles.',                                                            price:17.25, cat:'crispy-chow-mein',  img:I+'beef-and-broccoli-chow-mein.png',                      featured:false, sort:7  },
  { name:'M10. Beef in Black Bean Sauce Chow Mein 豉汁牛炒面',  slug:'beef-black-bean-chow-mein',           description:'Sliced beef with mushroom, bell pepper, and onion in black bean sauce on crispy noodles.',                 price:17.25, cat:'crispy-chow-mein',  img:I+'beef-in-black-bean-sauce-chow-mein.png',               featured:false, sort:8  },
  { name:'M2. Shredded Pork Chow Mein 肉丝炒面',                slug:'shredded-pork-chow-mein',             description:'With napa cabbage, bamboo shoot, and bean sprouts on crispy noodles.',                                   price:16.75, cat:'crispy-chow-mein',  img:I+'shredded-pork-chow-mein.png',                          featured:false, sort:9  },
  { name:'M9. Beef & Veggies Chow Mein 牛杂菜炒面',             slug:'beef-veg-chow-mein',                  description:'Sliced beef with mixed vegetables on crispy noodles.',                                                   price:17.25, cat:'crispy-chow-mein',  img:I+'beef-and-veggies-chow-mein.png',                       featured:false, sort:10 },
  { name:'M12. Curried Sliced Beef Chow Mein 咖喱牛炒面',       slug:'curried-beef-chow-mein',              description:'Sliced beef with bell pepper, onion, and carrot in curry sauce on crispy noodles. Spicy.',                price:17.25, cat:'crispy-chow-mein',  img:I+'curried-sliced-beef-chow-mein.png',                    featured:false, sort:11 },
  { name:'M13. Curried Sliced Chicken Chow Mein 咖喱鸡炒面',    slug:'curried-chicken-chow-mein',           description:'Sliced chicken with bell pepper, onion, and carrot in curry sauce on crispy noodles. Spicy.',              price:17.25, cat:'crispy-chow-mein',  img:I+'curried-sliced-chicken-chow-mein.png',                 featured:false, sort:12 },
  { name:'M6. Chicken & Broccoli Chow Mein 鸡百加利炒面',       slug:'chicken-broccoli-chow-mein',          description:'Sliced chicken and broccoli on crispy noodles.',                                                         price:17.25, cat:'crispy-chow-mein',  img:I+'chicken-and-broccoli-chow-mein.png',                   featured:false, sort:13 },
  { name:'M14. House Special Chow Mein 招牌炒面',               slug:'house-special-chow-mein',             description:'Fried noodles topped with prawns, squid, chicken, BBQ pork, broccoli, and black mushroom.',               price:19.50, cat:'crispy-chow-mein',  img:I+'house-special-chow-mein.png',                          featured:true,  sort:14 },
  { name:'M34. Prawn Chow Mein 虾球炒面',                       slug:'prawn-chow-mein',                     description:'Prawns, broccoli, bamboo shoot, black mushroom, and carrot on crispy noodles.',                          price:19.50, cat:'crispy-chow-mein',  img:I+'prawn-chow-mein.png',                                  featured:false, sort:15 },
  { name:'M15. Mixed Seafood Chow Mein 海鲜炒面',               slug:'mixed-seafood-chow-mein',             description:'Scallops, prawns, fish fillets, squid, and mixed vegetables on crispy noodles.',                         price:21.50, cat:'crispy-chow-mein',  img:I+'mixed-seafood-chow-mein.png',                          featured:false, sort:16 },
  { name:'M1. Shredded Chicken Chow Mein 鸡丝炒面',             slug:'shredded-chicken-chow-mein',          description:'With napa cabbage, bamboo shoot, and bean sprouts on crispy noodles.',                                   price:16.75, cat:'crispy-chow-mein',  img:I+'shredded-chicken-chow-mein.png',                       featured:false, sort:17 },

  // ── PORK ──
  { name:'P5. Steamed Spareribs in Black Bean Sauce 豉汁蒸骨',  slug:'steamed-spareribs-black-bean',        description:'Steamed pork spareribs in garlic black bean sauce.',                                                     price:22.00, cat:'pork', img:I+'steamed-spareribs-in-black-bean-sauce.png',            featured:false, sort:1  },
  { name:'P16. Fried Eggplant in Plum Sauce with Pork 酱爆茄子',slug:'eggplant-plum-sauce-pork',           description:'Eggplant with shredded pork and fried tofu in sweet dark plum sauce. Not spicy.',                        price:21.00, cat:'pork', img:I+'fried-eggplant-in-plum-sauce-with-pork.png',           featured:false, sort:2  },
  { name:'P2. Dry Garlic Boneless Pork 蒜子干猪',               slug:'dry-garlic-boneless-pork',            description:'Fried tender pork bits tossed with garlic.',                                                            price:21.00, cat:'pork', img:I+'dry-garlic-boneless-pork.png',                         featured:false, sort:3  },
  { name:'P3. Honey Garlic Spareribs 蜜蒜排骨',                 slug:'honey-garlic-spareribs',              description:'Fried bone-in pork spareribs in honey garlic sauce.',                                                   price:21.50, cat:'pork', img:I+'honey-garlic-spareribs.png',                           featured:true,  sort:4  },
  { name:'P8. Mandarin Sweet & Sour Pork 糖醋里脊',             slug:'mandarin-sweet-sour-pork',            description:'Tender crispy boneless pork in brown sweet and sour sauce.',                                            price:21.00, cat:'pork', img:I+'mandarin-sweet-and-sour-pork.png',                     featured:false, sort:5  },
  { name:'P14. Twice Cooked Pork with Cabbage 回锅肉',          slug:'twice-cooked-pork',                   description:'Tender pork with cabbage, bell pepper, and carrot in Szechuan spicy sauce.',                            price:21.00, cat:'pork', img:I+'twice-cooked-pork-with-cabbage.png',                   featured:false, sort:6  },
  { name:'P4. Honey Garlic Boneless Pork 蜜蒜里脊',             slug:'honey-garlic-boneless-pork',          description:'Fried boneless pork bits in honey garlic sauce.',                                                       price:21.50, cat:'pork', img:I+'honey-garlic-boneless-pork.png',                       featured:false, sort:7  },
  { name:'P7. Fried Pork Chops with Spiced Salt 椒盐猪扒',      slug:'fried-pork-chops-spiced-salt',        description:'Bone-in pork chops tossed in salt and pepper. Not spicy.',                                             price:22.00, cat:'pork', img:I+'fried-pork-chops-with-spiced-salt.png',                featured:false, sort:8  },
  { name:'P10. Pineapple Sweet & Sour Boneless Pork 咕噜肉',    slug:'pineapple-sweet-sour-pork',           description:'Breaded boneless pork with pineapple, bell pepper, and onion in red sweet and sour sauce.',              price:21.00, cat:'pork', img:I+'pineapple-sweet-and-sour-boneless-pork.png',           featured:true,  sort:9  },
  { name:'P6. Fried Spareribs with Spiced Salt 椒盐排骨',        slug:'fried-spareribs-spiced-salt',         description:'Fried bone-in pork spareribs. No garlic.',                                                             price:21.00, cat:'pork', img:I+'fried-spareribs-with-spiced-salt.png',                 featured:false, sort:10 },
  { name:'P13. Moo Shu Pork with 8 Pancakes 木须肉',            slug:'moo-shu-pork',                        description:'Chinese taco-style dish with pork, cabbage, and bean sprouts. Includes 8 pancakes.',                    price:21.00, cat:'pork', img:I+'moo-shu-pork-with-8-pancakes.png',                     featured:false, sort:11 },
  { name:'P11. Pork in Chili Garlic Sauce with Spinach 鱼香肉丝',slug:'pork-chili-garlic',                  description:'Shredded pork in spicy chili garlic sauce, served with cooked spinach.',                                 price:21.00, cat:'pork', img:I+'pork-in-chili-garlic-sauce-with-spinach.png',          featured:false, sort:12 },
  { name:'P17. Szechuan Spicy Green Beans with Pork 干煸四季豆', slug:'szechuan-green-beans-pork',          description:'Fried green beans with chef\'s special hot sauce. Spicy.',                                              price:21.00, cat:'pork', img:I+'szechuan-spicy-green-beans-with-pork.png',             featured:false, sort:13 },
  { name:'P12. Peking Pork Chops 京都猪扒',                     slug:'peking-pork-chops',                   description:'Bone-in pork chops with sweet and sour Peking-style sauce.',                                           price:22.00, cat:'pork', img:I+'peking-pork-chops.png',                                featured:false, sort:14 },
  { name:'P1. Dry Garlic Spareribs 蒜子排骨',                   slug:'dry-garlic-spareribs',                description:'Fried bone-in spareribs tossed with garlic.',                                                          price:21.00, cat:'pork', img:I+'dry-garlic-spareribs.png',                             featured:false, sort:15 },
  { name:'P15. Szechuan Spicy Eggplant with Pork 鱼香茄子',     slug:'szechuan-eggplant-pork',              description:'Spicy eggplant with shredded pork.',                                                                   price:21.00, cat:'pork', img:I+'szechuan-spicy-eggplant-with-pork.png',                featured:false, sort:16 },
  { name:'P9. Mandarin Sweet & Sour Pork with Garlic 蒜子里脊', slug:'mandarin-sweet-sour-pork-garlic',     description:'Fried tenderized boneless pork in brown sweet and sour sauce.',                                       price:21.00, cat:'pork', img:I+'mandarin-sweet-and-sour-pork-with-garlic.png',         featured:false, sort:17 },

  // ── SOUPS ──
  { name:'S2. Pork Wonton Soup 云吞汤',                          slug:'pork-wonton-soup',                    description:'12 pieces pork wonton in chicken broth.',                                                               price:12.50, cat:'soups', img:I+'pork-wonton-soup.png',                                featured:false, sort:1  },
  { name:'S10. Fish with Chinese Parsley Soup 西湖鱼肉羹',       slug:'fish-parsley-soup',                   description:'Thick soup with egg white.',                                                                             price:15.50, cat:'soups', img:I+'fish-with-chinese-parsley-soup.png',                   featured:false, sort:2  },
  { name:'S4. Minced Chicken & Corn Soup 鸡茸粟米汤',            slug:'chicken-corn-soup',                   description:'Thick soup with egg drop.',                                                                              price:14.00, cat:'soups', img:I+'minced-chicken-and-corn-soup.png',                     featured:false, sort:3  },
  { name:'S6. Sliced Beef & Tomato Soup 番茄牛肉汤',             slug:'beef-tomato-soup',                    description:'With egg drop.',                                                                                         price:14.00, cat:'soups', img:I+'sliced-beef-and-tomato-soup.png',                      featured:false, sort:4  },
  { name:'S3. Wor Wonton Soup 窝云吞汤',                         slug:'wor-wonton-soup',                     description:'12 pieces wonton with prawns, squid, chicken, BBQ pork, and vegetables.',                               price:15.50, cat:'soups', img:I+'wor-wonton-soup.png',                                 featured:false, sort:5  },
  { name:'S1. Hot & Sour Soup 酸辣汤',                           slug:'hot-sour-soup',                       description:'Tofu, pork, shrimp, and egg. Spicy.',                                                                   price:14.00, cat:'soups', img:I+'hot-and-sour-soup.png',                               featured:true,  sort:6  },
  { name:'S7. Mixed Seafood & Tofu Soup 海鲜豆腐汤',             slug:'seafood-tofu-soup',                   description:'Thick soup with egg white and mixed seafood.',                                                          price:15.50, cat:'soups', img:I+'mixed-seafood-and-tofu-soup.png',                      featured:false, sort:7  },
  { name:'S8. Mixed Meat & Egg Drop Soup 三丝蛋花汤',            slug:'mixed-meat-egg-drop-soup',            description:'Chicken, pork, vegetables, and egg drop.',                                                              price:14.00, cat:'soups', img:I+'mixed-meat-and-egg-drop-soup.png',                     featured:false, sort:8  },
  { name:'S9. Fried Tofu & Vermicelli Soup 油豆腐粉丝汤',        slug:'tofu-vermicelli-soup',                description:'With pork.',                                                                                             price:14.00, cat:'soups', img:I+'fried-tofu-and-vermicelli-soup.png',                   featured:false, sort:9  },
  { name:'S5. Pork, Spinach & Bean Curd Soup 肉丝豆腐汤',        slug:'pork-spinach-tofu-soup',              description:'With egg drop.',                                                                                         price:14.00, cat:'soups', img:I+'pork-spinach-and-bean-curd-soup.png',                  featured:false, sort:10 },
  { name:'Fish Maw / Crab Soup',                                  slug:'fish-maw-crab-soup',                  description:'Thick soup with egg white, fish maw, and crab meat.',                                                   price:19.50, cat:'soups', img:I+'fish-maw-crab-soup.png',                              featured:false, sort:11 },

  // ── BEEF ──
  { name:'B7. Sliced Beef with Mixed Vegetables 杂菜牛肉',       slug:'beef-mixed-veg',                      description:'Sliced beef with mixed vegetables.',                                                                    price:20.50, cat:'beef', img:I+'sliced-beef-with-mixed-vegetables.png',               featured:false, sort:1  },
  { name:'B4. Sliced Beef in Curry Sauce 咖喱牛肉',              slug:'beef-curry',                          description:'With bell peppers, onion, and carrot. Spicy.',                                                         price:21.00, cat:'beef', img:I+'sliced-beef-in-curry-sauce.png',                       featured:false, sort:2  },
  { name:'B1. Ginger Fried Beef 干煸牛肉丝',                     slug:'ginger-fried-beef',                   description:'Crispy beef strips in honey sauce with onion, bell pepper, and celery. Spicy.',                        price:21.50, cat:'beef', img:I+'ginger-fried-beef.png',                               featured:true,  sort:3  },
  { name:'B9. Sliced Beef with Gai Lan 芥兰牛肉',                slug:'beef-gai-lan',                        description:'Sliced beef sautéed with Chinese gai lan.',                                                            price:21.00, cat:'beef', img:I+'sliced-beef-with-gai-lan.png',                         featured:false, sort:4  },
  { name:'B2. Sliced Beef with Orange Flavour 陈皮牛肉',         slug:'beef-orange-flavour',                 description:'Tender beef slices with preserved orange flavour. Served with broccoli. Spicy.',                       price:21.50, cat:'beef', img:I+'sliced-beef-with-orange-flavour.png',                 featured:false, sort:5  },
  { name:'B10. Sliced Beef with Green Beans 豆仔牛肉',           slug:'beef-green-beans',                    description:'Sliced beef with green beans in garlic sauce.',                                                        price:21.00, cat:'beef', img:I+'sliced-beef-with-green-beans.png',                     featured:false, sort:6  },
  { name:'B6. Sliced Beef with Broccoli 百加利牛肉',             slug:'beef-broccoli',                       description:'Sliced beef with broccoli only.',                                                                      price:20.50, cat:'beef', img:I+'sliced-beef-with-broccoli.png',                       featured:true,  sort:7  },
  { name:'B12. Beef in Chili & Garlic Sauce with Spinach 鱼香牛肉丝',slug:'beef-chili-garlic',              description:'Shredded beef in spicy chili garlic sauce, served with steamed spinach.',                               price:21.00, cat:'beef', img:I+'beef-in-chili-garlic-sauce-with-spinach.png',          featured:false, sort:8  },
  { name:'B13. Szechuan Beef Stew 红烧牛肉',                     slug:'szechuan-beef-stew',                  description:'Tender stewed beef served with steamed head lettuce. Spicy.',                                          price:21.50, cat:'beef', img:I+'szechuan-beef-stew.png',                               featured:false, sort:9  },
  { name:'B8. Sliced Beef with Snow Peas 雪豆牛肉',              slug:'beef-snow-peas',                      description:'Sliced beef with pea pods, baby corn, and carrot.',                                                    price:21.00, cat:'beef', img:I+'sliced-beef-with-snow-peas.png',                       featured:false, sort:10 },
  { name:'B5. Sliced Beef in Black Bean Sauce 豉汁牛肉',         slug:'beef-black-bean',                     description:'With bell pepper, mushroom, and onion in garlic black bean sauce.',                                    price:21.00, cat:'beef', img:I+'sliced-beef-in-black-bean-sauce.png',                  featured:false, sort:11 },
  { name:'B11. Beef with Black Mushroom & Bamboo Shoot 双冬牛肉',slug:'beef-mushroom-bamboo',                description:'Sliced beef with black mushroom and bamboo shoot.',                                                    price:21.00, cat:'beef', img:I+'beef-with-black-mushroom-and-bamboo-shoot.png',        featured:false, sort:12 },
  { name:'B14. Beef with Tomato 番茄牛肉',                       slug:'beef-tomato',                         description:'Sliced beef with onion and tomato. No egg.',                                                           price:21.00, cat:'beef', img:I+'beef-with-tomato.png',                                 featured:false, sort:13 },
  { name:'B3. Sliced Beef with Ginger & Green Onions 姜葱牛肉',  slug:'beef-ginger-green-onions',            description:'Sliced beef sautéed with ginger and green onions.',                                                    price:21.00, cat:'beef', img:I+'sliced-beef-with-ginger-and-green-onions.png',          featured:false, sort:14 },

  // ── CHICKEN ──
  { name:'C5. Sliced Chicken with Mixed Vegetables 鸡片杂菜',    slug:'chicken-mixed-veg',                  description:'White meat chicken with mixed vegetables.',                                                             price:20.50, cat:'chicken', img:I+'sliced-chicken-with-mixed-vegetables.png',            featured:false, sort:1  },
  { name:'C1. Breaded Lemon Chicken 柠檬酥鸡',                  slug:'breaded-lemon-chicken',               description:'Served with lemon sauce on the side.',                                                                 price:21.00, cat:'chicken', img:I+'breaded-lemon-chicken.png',                           featured:true,  sort:2  },
  { name:'C4. House Special Chicken 四川干烹鸡',                 slug:'house-special-chicken',               description:'Boneless white meat chicken with mushroom, onion, and bell pepper in spicy house sauce.',               price:21.50, cat:'chicken', img:I+'house-special-chicken.png',                           featured:true,  sort:3  },
  { name:'C10. Sliced Chicken with Curry Sauce 咖喱鸡片',        slug:'chicken-curry',                       description:'White meat chicken with bell pepper, onion, and carrot in curry sauce. Spicy.',                        price:21.00, cat:'chicken', img:I+'sliced-chicken-with-curry-sauce.png',                  featured:false, sort:4  },
  { name:'C7. Sliced Chicken with Broccoli 鸡片百加利',          slug:'chicken-broccoli',                    description:'Sliced chicken with broccoli.',                                                                        price:20.50, cat:'chicken', img:I+'sliced-chicken-with-broccoli.png',                       featured:false, sort:5  },
  { name:'C9. Sliced Chicken with Gai Lan 鸡片芥兰',             slug:'chicken-gai-lan',                     description:'Sliced chicken sautéed with Chinese gai lan.',                                                         price:21.00, cat:'chicken', img:I+'sliced-chicken-with-gai-lan.png',                         featured:false, sort:6  },
  { name:'C18. Dai Ching Chicken Boneless 大千鸡（无骨）',        slug:'dai-ching-chicken-boneless',          description:'Boneless white meat chicken with green pepper and spicy Szechuan Dai Ching sauce.',                     price:23.50, cat:'chicken', img:I+'dai-ching-chicken-boneless.png',                         featured:false, sort:7  },
  { name:'C8. Sliced Chicken with Green Beans 鸡片豆仔',         slug:'chicken-green-beans',                 description:'Sliced chicken with green beans.',                                                                     price:21.00, cat:'chicken', img:I+'sliced-chicken-with-green-beans.png',                    featured:false, sort:8  },
  { name:'C20. Szechuan Fried Chicken with Garlic Sauce 四川油淋鸡',slug:'szechuan-fried-chicken-garlic',   description:'Half crispy fried chicken served with garlic sauce on the side.',                                       price:23.00, cat:'chicken', img:I+'szechuan-fried-chicken-with-garlic-sauce.png',         featured:false, sort:9  },
  { name:'C2. Breaded Almond Chicken 杏仁酥鸡',                  slug:'breaded-almond-chicken',              description:'Fried breaded chicken topped with crushed almonds.',                                                   price:21.00, cat:'chicken', img:I+'breaded-almond-chicken.png',                           featured:false, sort:10 },
  { name:'C11. Sliced Chicken with Black Bean Sauce 豉汁鸡片',   slug:'chicken-black-bean',                  description:'Sliced chicken in garlic black bean sauce.',                                                           price:21.00, cat:'chicken', img:I+'sliced-chicken-with-black-bean-sauce.png',              featured:false, sort:11 },
  { name:'C13. Diced Chicken with Cashews 腰果鸡丁',             slug:'chicken-cashews',                     description:'Diced chicken stir-fried with cashew nuts.',                                                          price:21.00, cat:'chicken', img:I+'diced-chicken-with-cashews.png',                         featured:false, sort:12 },
  { name:'C6. Sliced Chicken with Snow Peas 鸡片雪豆',           slug:'chicken-snow-peas',                   description:'Sliced chicken with snow peas.',                                                                       price:21.00, cat:'chicken', img:I+'sliced-chicken-with-snow-peas.png',                      featured:false, sort:13 },
  { name:'C3. Sweet & Sour Chicken Balls 咕噜鸡球',              slug:'sweet-sour-chicken-balls',            description:'Breaded chicken balls with pineapple sweet and sour sauce on the side.',                               price:21.00, cat:'chicken', img:I+'sweet-and-sour-chicken-balls.png',                       featured:false, sort:14 },
  { name:'C16. Kung Pow Chicken with Diced Veggies 宫保鸡丁',    slug:'kung-pow-chicken',                    description:'Diced chicken and vegetables with chili pepper and peanuts. Spicy.',                                  price:20.50, cat:'chicken', img:I+'kung-pow-chicken-with-diced-veggies.png',               featured:true,  sort:15 },
  { name:'C12. Sliced Chicken with Orange Flavor 陈皮鸡片',      slug:'chicken-orange-flavor',               description:'White meat chicken in spicy orange-flavoured sauce, served with broccoli.',                            price:21.50, cat:'chicken', img:I+'sliced-chicken-with-orange-flavor.png',                featured:false, sort:16 },
  { name:'C18. Dai Ching Chicken Bone-In 大千鸡（有骨）',         slug:'dai-ching-chicken-bone-in',           description:'Bone-in chicken with green pepper and spicy Szechuan Dai Ching sauce.',                               price:21.00, cat:'chicken', img:I+'dai-ching-chicken-bone-in.png',                          featured:false, sort:17 },
  { name:'C17. General Tso\'s Chicken Bone-In 左宗棠鸡（有骨）', slug:'general-tsos-chicken-bone-in',        description:'Bone-in chicken with green onion and chili pepper. Spicy.',                                           price:21.00, cat:'chicken', img:I+'general-tsos-chicken-bone-in.png',                      featured:false, sort:18 },
  { name:'C19. Fried Crispy Chicken with Shrimp Chips 炸子鸡',   slug:'fried-crispy-chicken-shrimp-chips',   description:'Half crispy fried chicken served with shrimp crackers.',                                               price:23.00, cat:'chicken', img:I+'fried-crispy-chicken-with-shrimp-chips.png',           featured:false, sort:19 },
  { name:'C14. Diced Chicken with Almonds 杏仁鸡丁',             slug:'chicken-almonds',                     description:'Diced chicken stir-fried with almonds.',                                                               price:21.00, cat:'chicken', img:I+'diced-chicken-with-almonds.png',                         featured:false, sort:20 },
  { name:'C15. Diced Chicken in Chili & Garlic Sauce with Spinach 鱼香鸡丁',slug:'chicken-chili-garlic',    description:'Spicy chili garlic chicken served with spinach.',                                                     price:21.00, cat:'chicken', img:I+'diced-chicken-in-chili-garlic-sauce-with-spinach.png',  featured:false, sort:21 },
  { name:'C17. General Tso\'s Chicken Boneless 左宗棠鸡（无骨）',slug:'general-tsos-chicken-boneless',       description:'Boneless chicken with green onion and chili pepper. Spicy.',                                          price:23.50, cat:'chicken', img:I+'general-tsos-chicken-boneless.png',                     featured:false, sort:22 },

  // ── APPETIZERS ──
  { name:'A1. Vegetarian Egg Rolls 素春卷',                      slug:'vegetarian-egg-rolls',                description:'Crispy vegetarian egg rolls. Priced per piece.',                                                       price:2.75,  cat:'appetizers', img:I+'vegetarian-egg-rolls.png',                         featured:false, sort:1  },
  { name:'A3. Deep Fried Chicken Wings 酥炸鸡翼',               slug:'deep-fried-chicken-wings',            description:'15 pieces, lightly floured and fried crispy. Served with spiced salt and lemon.',                     price:20.00, cat:'appetizers', img:I+'deep-fried-chicken-wings.png',                     featured:true,  sort:2  },
  { name:'A8. Beef Lettuce Wrap 牛肉生菜包',                     slug:'beef-lettuce-wrap',                   description:'Minced beef, bamboo shoot, celery, water chestnut, and carrot.',                                       price:22.00, cat:'appetizers', img:I+'beef-lettuce-wrap.png',                             featured:true,  sort:3  },
  { name:'A8. Chicken Lettuce Wrap 鸡肉生菜包',                  slug:'chicken-lettuce-wrap',                description:'Minced chicken, bamboo shoot, celery, water chestnut, and carrot.',                                    price:22.00, cat:'appetizers', img:I+'chicken-lettuce-wrap.png',                          featured:false, sort:4  },
  { name:'A8. Pork Lettuce Wrap 猪肉生菜包',                     slug:'pork-lettuce-wrap',                   description:'Minced pork, bamboo shoot, celery, water chestnut, and carrot.',                                       price:22.00, cat:'appetizers', img:I+'pork-lettuce-wrap.png',                              featured:false, sort:5  },
  { name:'A4. Barbecue Pork Slices 叉烧',                        slug:'bbq-pork-slices',                     description:'Marinated and roasted in-house. Served with honey sauce.',                                            price:14.50, cat:'appetizers', img:I+'barbecue-pork-slices.png',                          featured:false, sort:6  },
  { name:'A7. Deep Fried Wonton Chips 炸云皮',                   slug:'deep-fried-wonton-chips',             description:'Served with sweet and sour sauce. No meat.',                                                          price:13.75, cat:'appetizers', img:I+'deep-fried-wonton-chips.png',                       featured:false, sort:7  },
  { name:'A5. Five Spiced Beef Slices 五香牛肉',                 slug:'five-spiced-beef-slices',             description:'Cold cut.',                                                                                            price:14.50, cat:'appetizers', img:I+'five-spiced-beef-slices.png',                        featured:false, sort:8  },
  { name:'A2. Shrimp Egg Rolls 虾春卷',                          slug:'shrimp-egg-rolls',                    description:'Crispy shrimp egg rolls. Priced per piece.',                                                          price:3.50,  cat:'appetizers', img:I+'shrimp-egg-rolls.png',                              featured:false, sort:9  },
  { name:'A6. Deep Fried Pork Wonton 炸云吞',                    slug:'deep-fried-pork-wonton',              description:'12 pieces, served with sweet and sour sauce.',                                                        price:14.25, cat:'appetizers', img:I+'deep-fried-pork-wonton.png',                        featured:false, sort:10 },

  // ── OVER STEAMED RICE ──
  { name:'02. Chicken in Black Bean Sauce Over Rice 豉汁鸡烩饭',  slug:'osr-chicken-black-bean',     description:'Sliced chicken in garlic black bean sauce over steamed rice.',  price:15.00, cat:'over-steamed-rice', img:I+'chicken-in-black-bean-sauce-over-rice.png',  featured:false, sort:1  },
  { name:'05. Beef & Broccoli Over Rice 牛百加利烩饭',            slug:'osr-beef-broccoli',          description:'Sliced beef and broccoli over steamed rice.',                  price:15.00, cat:'over-steamed-rice', img:I+'beef-and-broccoli-over-rice.png',            featured:false, sort:2  },
  { name:'019. Steamed Rice 白饭',                                 slug:'osr-steamed-rice',           description:'Plain steamed white rice.',                                    price:2.50,  cat:'over-steamed-rice', img:I+'steamed-rice.png',                           featured:false, sort:3  },
  { name:'04. Chicken & Tomato Over Rice 番茄鸡烩饭',             slug:'osr-chicken-tomato',         description:'Sliced chicken and tomato over steamed rice.',                 price:15.00, cat:'over-steamed-rice', img:I+'chicken-and-tomato-over-rice.png',           featured:false, sort:4  },
  { name:'015. Mixed Vegetables & Fried Tofu Over Rice 杂菜豆腐烩饭',slug:'osr-mixed-veg-tofu',     description:'Vegetarian and vegan.',                                        price:15.50, cat:'over-steamed-rice', img:I+'mixed-vegetables-and-fried-tofu-over-rice.png',featured:false,sort:5 },
  { name:'01. Beef in Black Bean Sauce Over Rice 豉汁牛烩饭',     slug:'osr-beef-black-bean',        description:'Sliced beef in garlic black bean sauce over steamed rice.',    price:15.00, cat:'over-steamed-rice', img:I+'beef-in-black-bean-sauce-over-rice.png',     featured:false, sort:6  },
  { name:'018. Mixed Seafood & Vegetables Over Rice 油泡三鲜烩饭',slug:'osr-mixed-seafood-veg',      description:'Mixed seafood and vegetables over steamed rice.',               price:19.00, cat:'over-steamed-rice', img:I+'mixed-seafood-and-vegetables-over-rice.png', featured:false, sort:7  },
  { name:'07. Beef in Curry Sauce Over Rice 咖喱牛烩饭',          slug:'osr-beef-curry',             description:'Sliced beef in curry sauce over steamed rice.',                price:15.00, cat:'over-steamed-rice', img:I+'beef-in-curry-sauce-over-rice.png',          featured:false, sort:8  },
  { name:'016. Green Beans in Black Bean Sauce Over Rice 豉汁豆仔烩饭',slug:'osr-green-beans-black-bean',description:'Vegetarian and vegan.',                                  price:15.50, cat:'over-steamed-rice', img:I+'green-beans-in-black-bean-sauce-over-rice.png',featured:false,sort:9 },
  { name:'014. Beef & Green Beans Over Rice 豆仔牛烩饭',          slug:'osr-beef-green-beans',       description:'Sliced beef with green beans over steamed rice.',              price:15.50, cat:'over-steamed-rice', img:I+'beef-and-green-beans-over-rice.png',         featured:false, sort:10 },
  { name:'010. Chicken & Mixed Vegetables Over Rice 鸡杂菜烩饭',  slug:'osr-chicken-mixed-veg',      description:'Sliced chicken with mixed vegetables over steamed rice.',      price:15.00, cat:'over-steamed-rice', img:I+'chicken-and-mixed-vegetables-over-rice.png', featured:false, sort:11 },
  { name:'017. House Special Chicken Over Rice 干烹鸡烩饭',        slug:'osr-house-special-chicken',  description:'Spicy. House special chicken over steamed rice.',              price:16.50, cat:'over-steamed-rice', img:I+'house-special-chicken-over-rice.png',        featured:false, sort:12 },
  { name:'06. Chicken & Broccoli Over Rice 鸡百加利烩饭',         slug:'osr-chicken-broccoli',       description:'Sliced chicken and broccoli over steamed rice.',               price:15.00, cat:'over-steamed-rice', img:I+'chicken-and-broccoli-over-rice.png',         featured:false, sort:13 },
  { name:'03. Beef & Tomato Over Rice 番茄牛烩饭',                slug:'osr-beef-tomato',            description:'Sliced beef and tomato over steamed rice.',                    price:15.00, cat:'over-steamed-rice', img:I+'beef-and-tomato-over-rice.png',              featured:false, sort:14 },
  { name:'012. Chicken & Seasonal Vegetables Over Rice 时菜鸡烩饭',slug:'osr-chicken-seasonal-veg',  description:'Sliced chicken with seasonal vegetables over steamed rice.',   price:15.50, cat:'over-steamed-rice', img:I+'chicken-and-seasonal-vegetables-over-rice.png',featured:false,sort:15},
  { name:'09. Beef & Mixed Vegetables Over Rice 牛杂菜烩饭',      slug:'osr-beef-mixed-veg',         description:'Sliced beef with mixed vegetables over steamed rice.',         price:15.00, cat:'over-steamed-rice', img:I+'beef-and-mixed-vegetables-over-rice.png',    featured:false, sort:16 },
  { name:'013. Chicken & Green Beans Over Rice 豆仔鸡烩饭',       slug:'osr-chicken-green-beans',    description:'Sliced chicken with green beans over steamed rice.',           price:15.50, cat:'over-steamed-rice', img:I+'chicken-and-green-beans-over-rice.png',      featured:false, sort:17 },
  { name:'08. Chicken in Curry Sauce Over Rice 咖喱鸡烩饭',       slug:'osr-chicken-curry',          description:'Sliced chicken in curry sauce over steamed rice.',             price:15.00, cat:'over-steamed-rice', img:I+'chicken-in-curry-sauce-over-rice.png',       featured:false, sort:18 },
  { name:'011. Beef & Seasonal Vegetables Over Rice 时菜牛烩饭',  slug:'osr-beef-seasonal-veg',      description:'Sliced beef with seasonal vegetables over steamed rice.',      price:15.50, cat:'over-steamed-rice', img:I+'beef-and-seasonal-vegetables-over-rice.png', featured:false, sort:19 },

  // ── DIM SUM ──
  { name:'D2. Pork Shiu Mai 烧麦',                slug:'pork-shiu-mai',             description:'4 pieces.',                                               price:9.75,  cat:'dim-sum', img:I+'pork-shiu-mai.png',              featured:false, sort:1  },
  { name:'D4. Steamed Pork Dumplings 蒸饺',       slug:'steamed-pork-dumplings',    description:'10 pieces, served with ginger and red vinegar.',          price:12.75, cat:'dim-sum', img:I+'steamed-pork-dumplings.png',    featured:false, sort:2  },
  { name:'D8. Green Onion Pancakes 葱油饼',       slug:'green-onion-pancakes',      description:'Priced per piece.',                                       price:10.00, cat:'dim-sum', img:I+'green-onion-pancakes.png',       featured:false, sort:3  },
  { name:'D6. Fried Pork Dumplings 煎锅贴',       slug:'fried-pork-dumplings',      description:'10 pieces, served with chili sauce and white vinegar.',   price:12.75, cat:'dim-sum', img:I+'fried-pork-dumplings.png',      featured:false, sort:4  },
  { name:'D13. Sugar Filled Sweet Cakes 甜烧饼',  slug:'sugar-sweet-cakes',         description:'2 pieces.',                                               price:9.75,  cat:'dim-sum', img:I+'sugar-filled-sweet-cakes.png',  featured:false, sort:5  },
  { name:'D9. Hot Spicy Won Ton 红油抄手',         slug:'hot-spicy-wonton',          description:'12 boiled wontons in spicy sauce.',                       price:12.50, cat:'dim-sum', img:I+'hot-spicy-won-ton.png',          featured:false, sort:6  },
  { name:'D16. Sticky Rice Wraps 糯米鸡',         slug:'sticky-rice-wraps',         description:'2 pieces, with pork and egg yolk.',                       price:9.75,  cat:'dim-sum', img:I+'sticky-rice-wraps.png',          featured:false, sort:7  },
  { name:'D5. Steamed Vegetarian Dumplings 蒸素饺',slug:'steamed-veg-dumplings',    description:'10 pieces.',                                              price:12.75, cat:'dim-sum', img:I+'steamed-vegetarian-dumplings.png',featured:false,sort:8  },
  { name:'D7. Fried Vegetarian Dumplings 素锅贴', slug:'fried-veg-dumplings',       description:'10 pieces.',                                              price:12.75, cat:'dim-sum', img:I+'fried-vegetarian-dumplings.png', featured:false, sort:9  },
  { name:'D12. Red Bean Paste Cakes 豆沙蟹壳黄',  slug:'red-bean-paste-cakes',      description:'2 pieces.',                                               price:9.75,  cat:'dim-sum', img:I+'red-bean-paste-cakes.png',       featured:false, sort:10 },
  { name:'D1. Steamed Shrimp Dumplings 虾饺',     slug:'steamed-shrimp-dumplings',  description:'4 pieces.',                                               price:9.75,  cat:'dim-sum', img:I+'steamed-shrimp-dumplings.png',   featured:true,  sort:11 },
  { name:'D14. Red Bean Pastry 豆沙锅饼',         slug:'red-bean-pastry',           description:'Priced per piece.',                                       price:12.00, cat:'dim-sum', img:I+'red-bean-pastry.png',             featured:false, sort:12 },
  { name:'D17. Beef Tendon & Tripe 牛筋肚',       slug:'beef-tendon-tripe',         description:'Spicy.',                                                  price:11.75, cat:'dim-sum', img:I+'beef-tendon-and-tripe.png',      featured:false, sort:13 },
  { name:'D3. Steamed Pork Juicy Buns 小笼包',    slug:'steamed-pork-juicy-buns',   description:'10 pieces.',                                              price:12.75, cat:'dim-sum', img:I+'steamed-pork-juicy-buns.png',    featured:true,  sort:14 },
  { name:'D15. Mango Pudding 芒果布丁',            slug:'mango-pudding',             description:'Priced per piece.',                                       price:3.50,  cat:'dim-sum', img:'',                                 featured:false, sort:15 },

  // ── VEGETABLES ──
  { name:'V3. Sautéed Garlic Gai Lan 蒜蓉芥兰',                     slug:'sauteed-gai-lan',           description:'Gai lan sautéed with garlic.',                             price:20.50, cat:'vegetables', img:I+'sauteed-garlic-gai-lan.png',                    featured:false, sort:1  },
  { name:'V6. Vegetables with Tofu in Black Bean Sauce 豉汁杂菜豆腐',slug:'veg-tofu-black-bean',      description:'Mixed vegetables and tofu in black bean sauce.',            price:20.00, cat:'vegetables', img:I+'vegetables-with-tofu-in-black-bean-sauce.png',  featured:false, sort:2  },
  { name:'V4. Sautéed Four Kinds Seasonal Vegetables 炒四蔬',        slug:'four-seasonal-veg',         description:'Broccoli, snow peas, mushroom, and baby corn. Vegetarian.', price:20.50, cat:'vegetables', img:I+'sauteed-four-kinds-seasonal-vegetables.png',    featured:false, sort:3  },
  { name:'V7. Vegetable with Tofu in Curry Sauce 咖喱杂菜豆腐',      slug:'veg-tofu-curry',            description:'Mild spicy.',                                              price:20.00, cat:'vegetables', img:I+'vegetable-with-tofu-in-curry-sauce.png',         featured:false, sort:4  },
  { name:'V10. Sautéed Black Mushroom & Bamboo Shoot 炒双冬',        slug:'mushroom-bamboo-shoot',     description:'Vegetarian.',                                              price:20.50, cat:'vegetables', img:I+'sauteed-black-mushroom-and-bamboo-shoot.png',   featured:false, sort:5  },
  { name:'V1. Buddha\'s Feast Vegetables 得福素杂锦',                slug:'buddhas-feast',             description:'Assorted vegetables.',                                     price:19.50, cat:'vegetables', img:I+'buddhas-feast-vegetables.png',                  featured:true,  sort:6  },
  { name:'V5. Sautéed Green Beans in Black Bean Sauce 豉汁豆仔',     slug:'green-beans-black-bean',    description:'Green beans in garlic black bean sauce.',                  price:20.50, cat:'vegetables', img:I+'sauteed-green-beans-in-black-bean-sauce.png',   featured:false, sort:7  },
  { name:'V9. Szechuan Spicy Eggplant 鱼香茄子',                    slug:'szechuan-spicy-eggplant',   description:'Vegetarian and spicy.',                                    price:20.50, cat:'vegetables', img:I+'szechuan-spicy-eggplant.png',                   featured:false, sort:8  },
  { name:'V2. Sautéed Broccoli 清炒百加利',                          slug:'sauteed-broccoli',          description:'Lightly sautéed fresh broccoli.',                          price:19.50, cat:'vegetables', img:I+'sauteed-broccoli.png',                          featured:false, sort:9  },
  { name:'V8. Szechuan Spicy Green Beans 干煸四季豆',                slug:'szechuan-green-beans',      description:'Vegetarian and spicy.',                                    price:20.50, cat:'vegetables', img:I+'szechuan-spicy-green-beans.png',                featured:false, sort:10 },

  // ── SEAFOOD ──
  { name:'F22. Fried Fish Fillet with Spiced Salt 椒盐斑块',         slug:'fish-fillet-spiced-salt',      description:'Fried fish fillet with spiced salt.',                                         price:22.50, cat:'seafood', img:I+'fried-fish-fillet-with-spiced-salt.png',              featured:false, sort:1  },
  { name:'F13. Sautéed Prawns with Mixed Vegetables 杂菜虾球',       slug:'prawns-mixed-veg',             description:'Sautéed prawns with mixed vegetables.',                                      price:25.00, cat:'seafood', img:I+'sauteed-prawns-with-mixed-vegetables.png',           featured:true,  sort:2  },
  { name:'F2. Fish Fillet with Mixed Veggies 清炒鱼片',              slug:'fish-fillet-mixed-veg',        description:'Fish fillet with mixed vegetables.',                                         price:22.00, cat:'seafood', img:I+'fish-fillet-with-mixed-veggies.png',                 featured:false, sort:3  },
  { name:'F8. Kung Pao Squid with Diced Vegetables 宫保鲜鱿',        slug:'kung-pao-squid',               description:'Spicy.',                                                                     price:22.00, cat:'seafood', img:I+'kung-pao-squid-with-diced-vegetables.png',           featured:false, sort:4  },
  { name:'F6. Fried Squid with Spiced Salt 椒盐鲜鱿',                slug:'fried-squid-spiced-salt',      description:'Crispy fried squid with spiced salt.',                                       price:23.00, cat:'seafood', img:I+'fried-squid-with-spiced-salt.png',                   featured:false, sort:5  },
  { name:'F3. Fish Fillet with Sweet & Sour Sauce 糖醋鱼片',         slug:'fish-fillet-sweet-sour',       description:'Fish fillet in sweet and sour sauce.',                                       price:22.00, cat:'seafood', img:I+'fish-fillet-with-sweet-and-sour-sauce.png',          featured:false, sort:6  },
  { name:'F12. Sautéed Prawns with Cashews 腰果虾球',                slug:'prawns-cashews',               description:'Sautéed prawns with cashew nuts.',                                           price:25.00, cat:'seafood', img:I+'sauteed-prawns-with-cashews.png',                    featured:false, sort:7  },
  { name:'F14. Sautéed Prawns with Hot Chili Sauce 豆瓣虾球',        slug:'prawns-chili-sauce',           description:'Spicy.',                                                                     price:25.00, cat:'seafood', img:I+'sauteed-prawns-with-hot-chili-sauce.png',            featured:false, sort:8  },
  { name:'F1. Fish Fillet with Hot Chili Sauce 豆瓣鱼片',            slug:'fish-fillet-chili-sauce',      description:'Spicy.',                                                                     price:22.00, cat:'seafood', img:I+'fish-fillet-with-hot-chili-sauce.png',               featured:false, sort:9  },
  { name:'F7. Sautéed Squid with Black Bean Sauce 豉汁鲜鱿',         slug:'squid-black-bean',             description:'Squid in garlic black bean sauce.',                                          price:22.00, cat:'seafood', img:I+'sauteed-squid-with-black-bean-sauce.png',            featured:false, sort:10 },
  { name:'F11. Deep Fried Prawns with Sweet & Sour Sauce 椒盐壳虾',  slug:'deep-fried-prawns-sweet-sour', description:'Deep fried prawns with sweet and sour sauce.',                               price:25.00, cat:'seafood', img:I+'deep-fried-prawns-with-sweet-and-sour-sauce.png',    featured:false, sort:11 },
  { name:'F10. Prawns in Shell with Spiced Salt 蒜子壳虾',           slug:'prawns-shell-spiced-salt',     description:'Prawns in shell with spiced salt.',                                          price:25.00, cat:'seafood', img:I+'prawns-in-shell-with-spiced-salt.png',               featured:false, sort:12 },
  { name:'F4. Fish Fillet with Black Bean Sauce 豉汁鱼片',           slug:'fish-fillet-black-bean',       description:'Fish fillet in garlic black bean sauce.',                                    price:22.00, cat:'seafood', img:I+'fish-fillet-with-black-bean-sauce.png',              featured:false, sort:13 },
  { name:'F16. Sautéed Prawns with Black Bean Sauce 豉汁虾球',       slug:'prawns-black-bean',            description:'Sautéed prawns in garlic black bean sauce.',                                 price:25.00, cat:'seafood', img:I+'sauteed-prawns-with-black-bean-sauce.png',           featured:false, sort:14 },
  { name:'F15. Sautéed Prawns with Snow Peas 雪豆虾球',              slug:'prawns-snow-peas',             description:'Sautéed prawns with snow peas.',                                             price:25.00, cat:'seafood', img:I+'sauteed-prawns-with-snow-peas.png',                  featured:false, sort:15 },
  { name:'F21. Fried Fish Fillet with Cream Corn 粟米斑块',          slug:'fish-fillet-cream-corn',       description:'Fried fish fillet with cream corn sauce.',                                   price:22.50, cat:'seafood', img:I+'fried-fish-fillet-with-cream-corn.png',              featured:false, sort:16 },
  { name:'F18. Fried Mixed Seafood with Spiced Salt 椒盐三鲜',       slug:'fried-mixed-seafood-spiced-salt',description:'Fried mixed seafood with spiced salt.',                                  price:29.50, cat:'seafood', img:I+'fried-mixed-seafood-with-spiced-salt.png',           featured:false, sort:17 },
  { name:'F5. Chef\'s Special Fish Fillet 油泡鱼球',                 slug:'chefs-special-fish-fillet',    description:'Chef\'s special preparation of fish fillet.',                                price:24.00, cat:'seafood', img:I+'chefs-special-fish-fillet.png',                     featured:false, sort:18 },
  { name:'F17. Chef\'s Special Mixed Seafood Sauté 油泡三鲜',        slug:'chefs-special-mixed-seafood',  description:'Chef\'s special mixed seafood sauté.',                                       price:29.50, cat:'seafood', img:I+'chefs-special-mixed-seafood-saute.png',             featured:true,  sort:19 },

  // ── NOODLE SOUP ──
  { name:'N1. Wonton Noodle 云吞汤面',                    slug:'wonton-noodle-soup',          description:'12 pieces pork wonton with noodle soup.',                               price:14.50, cat:'noodle-soup', img:I+'wonton-noodle.png',                     featured:false, sort:1  },
  { name:'N10. Noodle with Meat Sauce 炸酱面',            slug:'noodle-meat-sauce',           description:'Not spicy. No soup.',                                                   price:13.50, cat:'noodle-soup', img:I+'noodle-with-meat-sauce.png',            featured:false, sort:2  },
  { name:'N6. Pork & Pickle Noodle 榨菜肉丝汤面',         slug:'pork-pickle-noodle',          description:'Served with spinach.',                                                  price:14.50, cat:'noodle-soup', img:I+'pork-and-pickle-noodle.png',            featured:false, sort:3  },
  { name:'N8. Mixed Vegetables Noodle 素菜汤面',          slug:'mixed-veg-noodle',            description:'Vegetarian.',                                                           price:14.50, cat:'noodle-soup', img:I+'mixed-vegetables-noodle.png',           featured:false, sort:4  },
  { name:'N2. Szechuan Beef Stew Noodle 红烧牛肉面',      slug:'szechuan-beef-stew-noodle',   description:'Spicy beef stew noodle soup with bok choy.',                            price:15.00, cat:'noodle-soup', img:I+'szechuan-beef-stew-noodle.png',         featured:false, sort:5  },
  { name:'N9. Shanghai Thick Noodle 上海汤面',            slug:'shanghai-thick-noodle',       description:'With pork.',                                                            price:14.50, cat:'noodle-soup', img:I+'shanghai-thick-noodle.png',             featured:false, sort:6  },
  { name:'N3. Fried Pork Chop Noodle 排骨汤面',           slug:'fried-pork-chop-noodle',      description:'Fried pork chop with noodle soup.',                                     price:15.00, cat:'noodle-soup', img:I+'fried-pork-chop-noodle.png',            featured:false, sort:7  },
  { name:'N5. Mixed Seafood Noodle 海鲜汤面',             slug:'mixed-seafood-noodle',        description:'Mixed seafood noodle soup.',                                            price:16.00, cat:'noodle-soup', img:I+'mixed-seafood-noodle.png',              featured:false, sort:8  },
  { name:'N11. Rice Cake with Pork 肉丝汤年糕',           slug:'rice-cake-pork-soup',         description:'Rice cake and pork in noodle soup.',                                    price:15.00, cat:'noodle-soup', img:I+'rice-cake-with-pork.png',               featured:false, sort:9  },
  { name:'N4. Tan Tan Noodle 担担面',                     slug:'tan-tan-noodle',              description:'Spicy noodle with Szechuan sesame paste and crushed peanut. No soup.', price:12.50, cat:'noodle-soup', img:I+'tan-tan-noodle.png',                   featured:false, sort:10 },
  { name:'N7. Pork & Salted Vegetable Noodle 雪菜肉丝汤面',slug:'pork-salted-veg-noodle',     description:'Served with spinach.',                                                  price:14.50, cat:'noodle-soup', img:I+'pork-and-salted-vegetable-noodle.png',  featured:false, sort:11 },

  // ── SIDES ──
  { name:'Cashews 腰果',          slug:'cashews',        description:'Add-on cashews.',       price:2.50, cat:'sides', img:I+'cashews.png',        featured:false, sort:1 },
  { name:'Almonds 杏仁',          slug:'almonds',        description:'Add-on almonds.',       price:2.50, cat:'sides', img:I+'almonds.png',        featured:false, sort:2 },
  { name:'Curry Sauce 咖喱酱',    slug:'curry-sauce',    description:'Side curry sauce.',     price:1.25, cat:'sides', img:I+'curry-sauce.png',    featured:false, sort:3 },
  { name:'Black Bean Sauce 豉汁', slug:'black-bean-sauce',description:'Side black bean sauce.',price:1.25,cat:'sides', img:I+'black-bean-sauce.png',featured:false, sort:4 },
  { name:'Prawn Crackers 虾片',   slug:'prawn-crackers', description:'Shrimp-flavoured chips.',price:5.00,cat:'sides', img:I+'prawn-crackers.png', featured:false, sort:5 },

  // ── DRINKS ──
  { name:'Bottled Water Dasani 矿泉水',   slug:'dasani-water',  description:'Dasani bottled water.',    price:2.75, cat:'drinks', img:I+'bottled-water-dasani.png',   featured:false, sort:1  },
  { name:'Barq\'s Root Beer 根汁啤酒',    slug:'root-beer',     description:'Canned.',                  price:1.75, cat:'drinks', img:I+'barqs-root-beer.png',         featured:false, sort:2  },
  { name:'Perrier Water 巴黎水',          slug:'perrier-water', description:'Sparkling mineral water.', price:3.75, cat:'drinks', img:I+'perrier-water.png',           featured:false, sort:3  },
  { name:'2 Liter Sprite Bottle 大雪碧',  slug:'2l-sprite',     description:'2 litre bottle.',          price:5.00, cat:'drinks', img:I+'2-liter-sprite-bottle.png',   featured:false, sort:4  },
  { name:'1 Liter Apple Juice 苹果汁',    slug:'1l-apple-juice',description:'1 litre apple juice.',     price:4.50, cat:'drinks', img:I+'1-liter-apple-juice.png',     featured:false, sort:5  },
  { name:'Nestea Cool Ice Tea 冰茶',       slug:'nestea-ice-tea',description:'Canned.',                  price:1.75, cat:'drinks', img:I+'nestea-cool-ice-tea.png',      featured:false, sort:6  },
  { name:'1 Liter Orange Juice 橙汁',     slug:'1l-orange-juice',description:'1 litre orange juice.',   price:4.50, cat:'drinks', img:I+'1-liter-orange-juice.png',    featured:false, sort:7  },
  { name:'Pepsi 百事可乐',                 slug:'pepsi',         description:'Canned.',                  price:1.75, cat:'drinks', img:I+'pepsi.png',                   featured:false, sort:8  },
  { name:'Orange Crush 橙汁汽水',          slug:'orange-crush',  description:'Canned.',                  price:1.75, cat:'drinks', img:I+'orange-crush.png',            featured:false, sort:9  },
  { name:'Diet Coke 健怡可乐',             slug:'diet-coke',     description:'Canned.',                  price:1.75, cat:'drinks', img:I+'diet-coke.png',               featured:false, sort:10 },
  { name:'Sprite 雪碧',                    slug:'sprite',        description:'Canned.',                  price:1.75, cat:'drinks', img:'',                               featured:false, sort:11 },
  { name:'2 Liter Coke Bottle 大可乐',    slug:'2l-coke',       description:'2 litre bottle.',          price:5.00, cat:'drinks', img:'',                               featured:false, sort:12 },
  { name:'Ginger Ale 姜汁汽水',            slug:'ginger-ale',    description:'Canned.',                  price:1.75, cat:'drinks', img:'',                               featured:false, sort:13 },
  { name:'Coke Zero 零度可乐',             slug:'coke-zero',     description:'Canned.',                  price:1.75, cat:'drinks', img:'',                               featured:false, sort:14 },
  { name:'Coke Classic 可口可乐',          slug:'coke-classic',  description:'Canned.',                  price:1.75, cat:'drinks', img:'',                               featured:false, sort:15 },

  // ── HOT POT ──
  { name:'H5. Eggplant with Chili & Garlic Hot Pot 漁香茄子煲',     slug:'hotpot-eggplant-chili',   description:'With pork.',                                                                                          price:22.00, cat:'hot-pot', img:I+'eggplant-with-chili-and-garlic-hot-pot.png',  featured:false, sort:1 },
  { name:'H1. Beef with Ginger & Green Onion Hot Pot 薑蔥牛肉煲',   slug:'hotpot-beef-ginger',      description:'Clay pot beef with ginger and green onion.',                                                          price:22.00, cat:'hot-pot', img:I+'beef-with-ginger-and-green-onion-hot-pot.png', featured:false, sort:2 },
  { name:'H6. Lamb Stew Bone-In Hot Pot 枝竹羊腩煲',                slug:'hotpot-lamb-stew',        description:'Bone-in lamb stew with water chestnut, black mushroom, bamboo shoot, and tofu wrap.',                price:30.00, cat:'hot-pot', img:I+'lamb-stew-bone-in-hot-pot.png',               featured:false, sort:3 },
  { name:'H2. Singing Chicken Bone-In Hot Pot 啫啫雞煲',            slug:'hotpot-singing-chicken',  description:'Bone-in chicken with ginger, onion, and black mushroom.',                                            price:22.00, cat:'hot-pot', img:I+'singing-chicken-bone-in-hot-pot.png',          featured:false, sort:4 },
  { name:'H4. Mixed Seafood with Fried Tofu Hot Pot 沙爹海鮮煲',    slug:'hotpot-seafood-tofu',     description:'Prawns, scallops, fish fillets, squid, tofu, vermicelli, and vegetables.',                           price:28.00, cat:'hot-pot', img:I+'mixed-seafood-with-fried-tofu-hot-pot.png',    featured:true,  sort:5 },
  { name:'H3. Mixed Veggies with Fried Tofu Hot Pot 雜菜豆腐煲',    slug:'hotpot-veg-tofu',         description:'Clay pot mixed vegetables with fried tofu.',                                                          price:21.00, cat:'hot-pot', img:I+'mixed-veggies-with-fried-tofu-hot-pot.png',    featured:false, sort:6 },

  // ── DUCK ──
  { name:'K1. Half BBQ Duck 烧鸭', slug:'half-bbq-duck', description:'Selected Fraser Valley free-range duck, marinated and roasted in-house. Half duck cut up and served with plum sauce.', price:27.00, cat:'duck', img:I+'half-bbq-duck.png', featured:true, sort:1 },

  // ── TOFU ──
  { name:'T6. Fried Bean Curd with Dai Ching Sauce 大千豆腐',              slug:'tofu-dai-ching',        description:'Fried tofu served with spicy sauce on the side. Vegetarian.',                price:20.00, cat:'tofu', img:I+'fried-bean-curd-with-dai-ching-sauce.png',           featured:false, sort:1 },
  { name:'T8. Fried Tofu with Vegetables in Black Bean Sauce 豉汁杂菜豆腐',slug:'tofu-veg-black-bean',   description:'Fried tofu and vegetables in black bean sauce.',                             price:20.00, cat:'tofu', img:I+'fried-tofu-with-vegetables-in-black-bean-sauce.png',  featured:false, sort:2 },
  { name:'T7. Fried Tofu with Chili Garlic Sauce Over Spinach 鱼香豆腐',   slug:'tofu-chili-garlic-spinach',description:'Fried tofu in chili garlic sauce served over spinach.',               price:20.00, cat:'tofu', img:I+'fried-tofu-with-chili-garlic-sauce-over-spinach.png', featured:false, sort:3 },
  { name:'T9. Fried Tofu with Vegetables in Curry Sauce 咖喱杂菜豆腐',     slug:'tofu-veg-curry',        description:'Mild spicy.',                                                                price:20.00, cat:'tofu', img:I+'fried-tofu-with-vegetables-in-curry-sauce.png',       featured:false, sort:4 },
  { name:'T2. Ma Po Tofu with Pork 麻婆豆腐',                              slug:'ma-po-tofu',            description:'Szechuan-style soft tofu with minced pork. Spicy.',                         price:20.00, cat:'tofu', img:I+'ma-po-tofu-with-pork.png',                          featured:true,  sort:5 },
  { name:'T5. Fried Bean Curd with Special Salt 椒盐豆腐',                 slug:'tofu-spiced-salt',      description:'Fried tofu tossed with salt and pepper. Vegetarian.',                       price:20.00, cat:'tofu', img:I+'fried-bean-curd-with-special-salt.png',              featured:false, sort:6 },
  { name:'T4. Fried Bean Curd with Meat Sauce 肉酱豆腐',                   slug:'tofu-meat-sauce',       description:'With meat sauce on the side.',                                               price:20.00, cat:'tofu', img:I+'fried-bean-curd-with-meat-sauce.png',                featured:false, sort:7 },
  { name:'T3. Fried Home Style Bean Curd with Mixed Seafood 海鲜家常豆腐', slug:'tofu-mixed-seafood',    description:'With scallops, prawns, fish fillets, and squid. Spicy.',                    price:26.00, cat:'tofu', img:I+'fried-home-style-bean-curd-with-mixed-seafood.png',  featured:false, sort:8 },
  { name:'T1. Braised Bean Curd with Black Mushroom 冬菇豆腐',             slug:'braised-tofu-mushroom', description:'Soft tofu with black mushroom and bamboo shoot. Vegetarian.',                price:20.00, cat:'tofu', img:I+'braised-bean-curd-with-black-mushroom.png',          featured:false, sort:9 },

  // ── EGG ──
  { name:'E1. Fried Eggs with Prawns 蝦仁炒蛋',              slug:'fried-eggs-prawns',      description:'Stir-fried eggs with fresh prawns.',                                 price:23.00, cat:'egg', img:I+'fried-eggs-with-prawns.png',             featured:false, sort:1 },
  { name:'E2. Vegetarian Egg Foo Yong with Gravy 素菜芙蓉蛋',slug:'veg-egg-foo-yong',      description:'Chopped vegetables, green onion, bean sprouts, and egg.',           price:19.00, cat:'egg', img:I+'vegetarian-egg-foo-yong-with-gravy.png',  featured:false, sort:2 },
  { name:'E3. Chicken Egg Foo Yong with Gravy 雞絲芙蓉蛋',   slug:'chicken-egg-foo-yong',  description:'Shredded chicken, onion, green onion, bean sprouts, and egg.',       price:20.00, cat:'egg', img:I+'chicken-egg-foo-yong-with-gravy.png',     featured:false, sort:3 },
  { name:'E5. BBQ Pork Egg Foo Yong with Gravy 叉燒芙蓉蛋',  slug:'bbq-pork-egg-foo-yong', description:'BBQ pork, onion, green onion, bean sprouts, and egg.',               price:20.00, cat:'egg', img:I+'bbq-pork-egg-foo-yong-with-gravy.png',    featured:false, sort:4 },
  { name:'E4. Shrimp Egg Foo Yong with Gravy 蝦仁芙蓉蛋',    slug:'shrimp-egg-foo-yong',   description:'Shrimp, onion, green onion, bean sprouts, and egg.',                 price:21.00, cat:'egg', img:I+'shrimp-egg-foo-yong-with-gravy.png',      featured:false, sort:5 },
];

// ─── SEED RUNNER ──────────────────────────────────────────────────────────────
async function seed() {
  await mongoose.connect(URI);
  console.log('✅ Connected to MongoDB at', URI);

  await Cat.deleteMany({});
  await Item.deleteMany({});
  console.log('🗑️  Cleared existing data');

  const createdCats = await Cat.insertMany(CATS);
  const catMap: Record<string, mongoose.Types.ObjectId> = {};
  for (const c of createdCats) {
    const cc = c as unknown as { slug: string; _id: mongoose.Types.ObjectId };
    catMap[cc.slug] = cc._id;
  }
  console.log(`📂 Created ${createdCats.length} categories`);

  const docs = ITEMS.map(({ cat, img, featured, sort, ...rest }) => ({
    ...rest,
    category: catMap[cat],
    image: img || '',
    isFeatured: featured,
    sortOrder: sort,
    isAvailable: true,
  }));

  const created = await Item.insertMany(docs);
  console.log(`🍜 Created ${created.length} menu items`);

  console.log('\n── Category breakdown ──');
  for (const c of CATS) {
    const n = ITEMS.filter(i => i.cat === c.slug).length;
    console.log(`  ${c.name.padEnd(42)} ${n} items`);
  }

  await mongoose.disconnect();
  console.log('\n🎉 Database seeded successfully!');
}

seed().catch(err => { console.error('❌ Seed failed:', err.message); process.exit(1); });
