import { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    name: 'Cadillac Escalade',
    category: 'Luxury SUV',
    image: 'https://images.pexels.com/photos/244206/pexels-photo-244206.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 120,
    minimumHours: 1,
    passengers: 6,
    luggage: 4,
    description: 'Experience ultimate luxury with our flagship Cadillac Escalade. Perfect for executive travel and special occasions.',
    features: ['Premium Leather Seats', 'Climate Control', 'WiFi', 'Premium Sound System', 'Privacy Glass'],
  },
  {
    id: '2',
    name: 'GMC Yukon Denali',
    category: 'Premium SUV',
    image: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 110,
    minimumHours: 1,
    passengers: 7,
    luggage: 5,
    description: 'Sophisticated comfort meets versatility. The GMC Yukon Denali offers spacious luxury for larger groups.',
    features: ['Spacious Interior', 'Premium Audio', 'Ambient Lighting', 'Power Liftgate', 'Advanced Safety'],
  },
  {
    id: '3',
    name: 'Mercedes S-Class',
    category: 'Executive Sedan',
    image: 'https://images.pexels.com/photos/120049/pexels-photo-120049.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 130,
    minimumHours: 1,
    passengers: 4,
    luggage: 3,
    description: 'The pinnacle of automotive luxury. Arrive in style with the iconic Mercedes S-Class.',
    features: ['Massage Seats', 'Burmester Sound', 'Executive Seating', 'Air Suspension', 'Panoramic Roof'],
  },
  {
    id: '4',
    name: 'Stretch Limousine',
    category: 'Ultra Luxury',
    image: 'https://images.pexels.com/photos/244206/pexels-photo-244206.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 200,
    minimumHours: 5,
    passengers: 10,
    luggage: 4,
    description: 'Make a grand entrance with our elegant stretch limousine. Perfect for weddings and VIP events.',
    features: ['Bar Service', 'LED Lighting', 'Privacy Partition', 'Premium Entertainment', 'Fiber Optic Ceiling'],
  },
  {
    id: '5',
    name: 'Chevrolet Suburban',
    category: 'Family SUV',
    image: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 95,
    minimumHours: 1,
    passengers: 8,
    luggage: 6,
    description: 'Spacious and comfortable, ideal for family trips and group travel with ample luggage space.',
    features: ['Third Row Seating', 'Large Cargo Space', 'USB Charging', 'Rear Entertainment', 'Tri-Zone Climate'],
  },
  {
    id: '6',
    name: 'Lincoln Navigator',
    category: 'Luxury SUV',
    image: 'https://images.pexels.com/photos/1592384/pexels-photo-1592384.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 125,
    minimumHours: 1,
    passengers: 7,
    luggage: 5,
    description: 'American luxury at its finest. The Lincoln Navigator combines comfort with commanding presence.',
    features: ['Reclining Seats', 'Premium Materials', 'Advanced Tech', 'Perfect Position Seats', 'Revel Audio'],
  },
  {
    id: '7',
    name: 'Black Escalade',
    category: 'Black SUV',
    image: 'https://images.pexels.com/photos/244206/pexels-photo-244206.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 140,
    minimumHours: 1,
    passengers: 6,
    luggage: 4,
    description: 'Our signature all-black Cadillac Escalade — the ultimate statement in executive luxury. Tinted windows, blacked-out trim, and a commanding presence on every road.',
    features: ['All-Black Exterior', 'Tinted Privacy Glass', 'Premium Leather', 'WiFi Hotspot', 'Ambient Lighting'],
  },
  {
    id: '8',
    name: 'Black Yukon XL',
    category: 'Black SUV',
    image: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 130,
    minimumHours: 1,
    passengers: 8,
    luggage: 6,
    description: 'The blacked-out GMC Yukon XL delivers maximum space without sacrificing style. Ideal for group transfers, corporate events, and airport runs with extra luggage.',
    features: ['Extended Wheelbase', 'All-Black Trim', 'Third Row Seating', 'Dual Climate Zones', 'Power Running Boards'],
  },
  {
    id: '9',
    name: 'Black Suburban',
    category: 'Black SUV',
    image: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 115,
    minimumHours: 1,
    passengers: 8,
    luggage: 7,
    description: 'The iconic all-black Chevrolet Suburban — trusted by executives and security details worldwide. Massive interior, smooth ride, and an unmistakable black-on-black finish.',
    features: ['Black-on-Black Finish', 'Massive Cargo Space', 'Rear Entertainment', 'USB Charging Ports', 'Advanced Safety Suite'],
  },
  {
    id: '10',
    name: 'Black Sprinter Van',
    category: 'Luxury Van',
    image: 'https://images.pexels.com/photos/2533092/pexels-photo-2533092.jpeg?auto=compress&cs=tinysrgb&w=1200',
    pricePerHour: 160,
    minimumHours: 1,
    passengers: 12,
    luggage: 10,
    description: 'Our executive black Mercedes Sprinter Van is the go-to for large group transfers, airport shuttles, and corporate events. Fully customized interior with premium seating for up to 12 passengers.',
    features: ['12-Passenger Capacity', 'Custom Interior', 'Individual Leather Seats', 'Panoramic Windows', 'Onboard WiFi & USB'],
  },
];

export const experienceHighlights = [
  {
    title: 'Professional Chauffeurs',
    description: 'Experienced, licensed, and background-checked drivers',
    icon: 'shield'
  },
  {
    title: 'Luxury Fleet',
    description: 'Premium vehicles maintained to the highest standards',
    icon: 'car'
  },
  {
    title: 'Always On Time',
    description: 'Punctuality and reliability you can count on',
    icon: 'clock'
  },
  {
    title: '24/7 Service',
    description: 'Available around the clock for your convenience',
    icon: 'phone'
  }
];
