export const services = [
  {
    id: 'engine-repair',
    title: 'Engine Repair',
    shortDesc: 'Complete engine diagnostics, rebuild and repair by certified specialists.',
    fullDesc: 'Our engine specialists diagnose, repair, and rebuild engines of all makes and models. From minor tune-ups to full engine overhauls, we use the latest diagnostic technology to ensure your engine runs at peak performance.',
    icon: `...`,
    price: 'From $25 - $180',
    duration: '2-8 hours',
  },
  {
    id: 'tire-change',
    title: 'Tire Change',
    shortDesc: 'Professional tire mounting, balancing and alignment services.',
    fullDesc: 'Get your tires mounted, balanced, and aligned by our expert technicians...',
    icon: `...`,
    price: 'From $10 - $35',
    duration: '30-60 min',
  },
  {
    id: 'oil-change',
    title: 'Oil Change',
    shortDesc: 'Full synthetic and conventional oil change with filter replacement.',
    fullDesc: 'Regular oil changes are essential to keep your engine healthy...',
    icon: `...`,
    price: 'From $15 - $60',
    duration: '30-45 min',
  },
  {
    id: 'brake-service',
    title: 'Brake Service',
    shortDesc: 'Brake pad replacement, rotor resurfacing and hydraulic system service.',
    fullDesc: 'Your brakes are your most critical safety system...',
    icon: `...`,
    price: 'From $30 - $120',
    duration: '1-2 hours',
  },
  {
    id: 'diagnostics',
    title: 'Car Diagnostics',
    shortDesc: 'Advanced OBD computer diagnostics to identify all vehicle issues.',
    fullDesc: 'Using the latest OBD-II diagnostic tools...',
    icon: `...`,
    price: 'From $10 - $50',
    duration: '1-2 hours',
  },
  {
    id: 'suspension',
    title: 'Suspension Repair',
    shortDesc: 'Shock absorbers, struts, springs and complete suspension overhaul.',
    fullDesc: 'A well-maintained suspension system ensures comfort...',
    icon: `...`,
    price: 'From $40 - $150',
    duration: '2-4 hours',
  },
  {
    id: 'body-paint',
    title: 'Body Paint Work',
    shortDesc: 'Professional bodywork, dent removal and custom paint finishing.',
    fullDesc: 'Restore your vehicle\'s appearance with our professional bodywork...',
    icon: `...`,
    price: 'From $80 - $300',
    duration: '1-3 days',
  },
  {
    id: 'ac-repair',
    title: 'AC Repair',
    shortDesc: 'Air conditioning regas, compressor repair and full HVAC service.',
    fullDesc: 'Stay cool in Pakistan\'s heat with our comprehensive AC repair...',
    icon: `...`,
    price: 'From $25 - $120',
    duration: '1-3 hours',
  },
]